export const latestArticleData = [
    {
        id: 1,
        img: "/images/article-featured-img.jpg",
        title: "Society for Healthcare & Research Development",
        excerpt:
            "Intradermal Immunoglobulin E (IgE) Injection in a Specific Interval With Emollient in the Control of Chronic Idiopathic Urticaria and Allergic Rhinitis",
        date: "6 Nov, 2023",
        category: "RESEARCH",
        author: "Pro. Dr. S M A Shamim",
        designation: "DOI:10.7759/cureus.48358",
        authorImg: "/images/author-image.png",
        isSave: false,
    },
    {
        id: 2,
        img: "/images/article-featured-img.jpg",
        title: "Annals of International Medical and Dental Research",
        excerpt:
            "Side Effects of Oral Valacyclovir and Oral Acyclovir in the Treatment of Herpes Zoster",
        date: "Nov-Dec 2022",
        category: "CLINICAL STUDY",
        author: "Pro. Dr. S M A Shamim",
        designation: "Vol. 8, Issue-6",
        authorImg: "/images/author-image.png",
        isSave: false,
    },
    {
        id: 3,
        img: "/images/article-featured-img.jpg",
        title: "International Journal of Research in Dermatology",
        excerpt:
            "Combination of systemic terbinafine (250 mg) twice daily and itraconazole (100 mg) twice in a pulse dose in resistant tinea infection",
        date: "March-April 2022",
        category: "TREATMENT",
        author: "Pro. Dr. S M A Shamim",
        designation: "Vol. 8, Issue-2",
        authorImg: "/images/author-image.png",
        isSave: false,
    },
    {
        id: 4,
        img: "/images/article-featured-img.jpg",
        title: "National Library of Medicine",
        excerpt:
            '"Lockdown Dermatoses" during COVID-19-A Series of 127 Patients from the Indian Subcontinent',
        date: "28 Feb, 2022",
        category: "CASE STUDY",
        author: "Pro. Dr. S M A Shamim",
        designation: "Vol. 20, Issue-1",
        authorImg: "/images/author-image.png",
        isSave: false,
    },
    {
        id: 5,
        img: "/images/article-featured-img.jpg",
        title: "Journal of Clinical and Diagnostic Research",
        excerpt:
            "Efficacy of Topical Corticosteroids in Combination with Antifungal Therapy for Seborrheic Dermatitis Treatment",
        date: "15 Jan, 2022",
        category: "TREATMENT",
        author: "Pro. Dr. S M A Shamim",
        designation: "Vol. 16, Issue-1",
        authorImg: "/images/author-image.png",
        isSave: false,
    },
    {
        id: 6,
        img: "/images/article-featured-img.jpg",
        title: "Asian Journal of Dermatological Sciences",
        excerpt:
            "Comparative Study of Pulse Therapy versus Continuous Therapy in Chronic Plaque Psoriasis Management",
        date: "Oct-Dec 2021",
        category: "CLINICAL STUDY",
        author: "Pro. Dr. S M A Shamim",
        designation: "Vol. 12, Issue-4",
        authorImg: "/images/author-image.png",
        isSave: false,
    },
    {
        id: 7,
        img: "/images/article-featured-img.jpg",
        title: "Bangladesh Medical Journal",
        excerpt:
            "Prevalence and Risk Factors of Contact Dermatitis Among Healthcare Workers in Dhaka Medical College",
        date: "22 Sep, 2021",
        category: "RESEARCH",
        author: "Pro. Dr. S M A Shamim",
        designation: "Vol. 45, Issue-3",
        authorImg: "/images/author-image.png",
        isSave: false,
    },
    {
        id: 8,
        img: "/images/article-featured-img.jpg",
        title: "Indian Journal of Dermatology, Venereology and Leprology",
        excerpt:
            "Novel Approach in Treating Vitiligo with Narrow-band UV-B Phototherapy Combined with Topical Calcineurin Inhibitors",
        date: "Aug 2021",
        category: "TREATMENT",
        author: "Pro. Dr. S M A Shamim",
        designation: "Vol. 87, Issue-4",
        authorImg: "/images/author-image.png",
        isSave: false,
    },
    {
        id: 9,
        img: "/images/article-featured-img.jpg",
        title: "Dermatology Research and Practice",
        excerpt:
            "Clinical Outcomes of Oral Isotretinoin in Moderate to Severe Acne Vulgaris: A Prospective Study",
        date: "12 Jul, 2021",
        category: "CLINICAL STUDY",
        author: "Pro. Dr. S M A Shamim",
        designation: "Article ID: 9876543",
        authorImg: "/images/author-image.png",
        isSave: false,
    },
    {
        id: 10,
        img: "/images/article-featured-img.jpg",
        title: "International Journal of Trichology",
        excerpt:
            "Androgenetic Alopecia in Young Adults: Early Intervention Strategies and Treatment Outcomes",
        date: "May-Jun 2021",
        category: "SPECIALIZED",
        author: "Pro. Dr. S M A Shamim",
        designation: "Vol. 13, Issue-3",
        authorImg: "/images/author-image.png",
        isSave: false,
    },
    {
        id: 11,
        img: "/images/article-featured-img.jpg",
        title: "Journal of Pakistan Association of Dermatologists",
        excerpt:
            "Cutaneous Manifestations in Diabetes Mellitus: A Cross-sectional Study in Tertiary Care Hospital",
        date: "April 2021",
        category: "CLINICAL STUDY",
        author: "Pro. Dr. S M A Shamim",
        designation: "Vol. 31, Issue-2",
        authorImg: "/images/author-image.png",
        isSave: false,
    },
    {
        id: 12,
        img: "/images/article-featured-img.jpg",
        title: "Skin Pharmacology and Physiology",
        excerpt:
            "Molecular Mechanisms of Topical Retinoids in Photoaging Prevention and Treatment",
        date: "18 Mar, 2021",
        category: "RESEARCH",
        author: "Pro. Dr. S M A Shamim",
        designation: "Vol. 34, Issue-2",
        authorImg: "/images/author-image.png",
        isSave: false,
    },
    {
        id: 13,
        img: "/images/article-featured-img.jpg",
        title: "Clinical, Cosmetic and Investigational Dermatology",
        excerpt:
            "Safety and Efficacy of Fractional CO2 Laser in Treatment of Acne Scars: A Randomized Controlled Trial",
        date: "Feb 2021",
        category: "COSMETIC",
        author: "Pro. Dr. S M A Shamim",
        designation: "Vol. 14, Pages 127-135",
        authorImg: "/images/author-image.png",
        isSave: false,
    },
    {
        id: 14,
        img: "/images/article-featured-img.jpg",
        title: "Journal of Cosmetic Dermatology",
        excerpt:
            "Comparative Analysis of Different Chemical Peels in Melasma Treatment: A Multi-center Study",
        date: "25 Jan, 2021",
        category: "COSMETIC",
        author: "Pro. Dr. S M A Shamim",
        designation: "Vol. 20, Issue-1",
        authorImg: "/images/author-image.png",
        isSave: false,
    },
    {
        id: 15,
        img: "/images/article-featured-img.jpg",
        title: "Pediatric Dermatology",
        excerpt:
            "Atopic Dermatitis in Bangladeshi Children: Environmental Factors and Treatment Response Patterns",
        date: "Dec 2020",
        category: "SPECIALIZED",
        author: "Pro. Dr. S M A Shamim",
        designation: "Vol. 37, Issue-6",
        authorImg: "/images/author-image.png",
        isSave: false,
    },
    {
        id: 16,
        img: "/images/article-featured-img.jpg",
        title: "Archives of Dermatological Research",
        excerpt:
            "Immunohistochemical Analysis of Basal Cell Carcinoma: Correlation with Clinical Subtypes and Treatment Response",
        date: "14 Nov, 2020",
        category: "RESEARCH",
        author: "Pro. Dr. S M A Shamim",
        designation: "Vol. 312, Issue-9",
        authorImg: "/images/author-image.png",
        isSave: false,
    },
    {
        id: 17,
        img: "/images/article-featured-img.jpg",
        title: "Contact Dermatitis Journal",
        excerpt:
            "Occupational Contact Dermatitis Among Construction Workers: Identification of Common Allergens and Prevention Strategies",
        date: "Oct 2020",
        category: "SPECIALIZED",
        author: "Pro. Dr. S M A Shamim",
        designation: "Vol. 83, Issue-4",
        authorImg: "/images/author-image.png",
        isSave: false,
    },
    {
        id: 18,
        img: "/images/article-featured-img.jpg",
        title: "Mycoses International Journal",
        excerpt:
            "Emerging Antifungal Resistance in Dermatophyte Infections: Clinical Implications and Treatment Modifications",
        date: "8 Sep, 2020",
        category: "RESEARCH",
        author: "Pro. Dr. S M A Shamim",
        designation: "Vol. 63, Issue-9",
        authorImg: "/images/author-image.png",
        isSave: false,
    },
    {
        id: 19,
        img: "/images/article-featured-img.jpg",
        title: "Wound Repair and Regeneration",
        excerpt:
            "Advanced Wound Dressing Technologies in Diabetic Foot Ulcer Management: A Comparative Clinical Study",
        date: "Aug 2020",
        category: "SPECIALIZED",
        author: "Pro. Dr. S M A Shamim",
        designation: "Vol. 28, Issue-4",
        authorImg: "/images/author-image.png",
        isSave: false,
    },
    {
        id: 20,
        img: "/images/article-featured-img.jpg",
        title: "Photodermatology, Photoimmunology & Photomedicine",
        excerpt:
            "Sun Protection Behavior and Skin Cancer Awareness Among Medical Students in Bangladesh: A Survey-based Study",
        date: "23 Jul, 2020",
        category: "CASE STUDY",
        author: "Pro. Dr. S M A Shamim",
        designation: "Vol. 36, Issue-4",
        authorImg: "/images/author-image.png",
        isSave: false,
    },
];