import Footer from "@/components/Footer/Footer";
import Header from "@/components/Header/Header";
import { Anton, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";

const plusJakartaSans = Plus_Jakarta_Sans({
    variable: "--font-plus-jakarta-sans",
    subsets: ["latin"],
});

const anton = Anton({
    variable: "--font-anton",
    subsets: ["latin"],
    weight: ["400"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={`${anton.variable} ${plusJakartaSans.variable}  antialiased`}
            >
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    );
}
