export const latestArticleData = [
  {
    id: 1,
    img: "/images/article-featured-img.jpg",
    title: "Society for Healthcare & Research Development",
    excerpt:
      "COSDERMINDIA 2024, 27th Annual Congress of Cosmetic Dermatology Society India (CDSI), Mumbai, India",
    date: "1 to 3 Aug, 2024",
    category: "SEMINAR, SYMPOSIUM, CONFERENCE",
    author: "Pro. Dr. S M A Shamim",
    designation: "INDIA",
    authorImg: "/images/author-image.png",
    isSave: false,
  },
  {
    id: 2,
    img: "/images/article-featured-img.jpg",
    title: "Annals of International Medical and Dental Research",
    excerpt:
      "DERMA MeDeCON 2024 by SAARC AAD In UAE, Conrad, Dubai",
    date: "10 May, 2024",
    category: "SEMINAR, SYMPOSIUM, CONFERENCE",
    author: "Pro. Dr. S M A Shamim",
    designation: "DHAKA",
    authorImg: "/images/author-image.png",
    isSave: false,
  },
  {
    id: 3,
    img: "/images/article-featured-img.jpg",
    title: "International Journal of Research in Dermatology",
    excerpt:
      "DSCON 2024, 10th International Conference & Live Demonstration Arranged by Society of Dermatologic Surgeons of Bangladesh (SDSB), InterContinental, Dhaka",
    date: "7 May, 2024",
    category: "SEMINAR, SYMPOSIUM, CONFERENCE",
    author: "Pro. Dr. S M A Shamim",
    designation: "DHAKA",
    authorImg: "/images/author-image.png",
    isSave: false,
  },
  {
    id: 4,
    img: "/images/article-featured-img.jpg",
    title: "National Library of Medicine",
    excerpt:
      "AMWC 2023, 21st Aesthetic & Anti-Aging Medicine World Congress – The World`s Largest Event for “Global Aging Management”, Montecarlo, Monaco",
    date: "28 Feb, 2022",
    category: "SEMINAR, SYMPOSIUM, CONFERENCE",
    author: "Pro. Dr. S M A Shamim",
    designation: "MONACO",
    authorImg: "/images/author-image.png",
    isSave: false,
  },
  {
    id: 5,
    img: "/images/article-featured-img.jpg",
    title: "Society for Healthcare & Research Development",
    excerpt:
      "Intradermal Immunoglobulin E (IgE) Injection in a Specific Interval With Emollient in the Control of Chronic Idiopathic Urticaria and Allergic Rhinitis",
    date: "6 Nov, 2023",
    category: "ARTICLES",
    author: "Pro. Dr. S M A Shamim",
    designation: "DOI:10.7759/cureus.48358",
    authorImg: "/images/author-image.png",
    isSave: false,
  },
  {
    id: 6,
    img: "/images/article-featured-img.jpg",
    title: "Annals of International Medical and Dental Research",
    excerpt:
      "Side Effects of Oral Valacyclovir and Oral Acyclovir in the Treatment of Herpes Zoster",
    date: "Nov-Dec 2022",
    category: "ARTICLES",
    author: "Pro. Dr. S M A Shamim",
    designation: "Vol. 8, Issue-6",
    authorImg: "/images/author-image.png",
    isSave: false,
  },
  {
    id: 7,
    img: "/images/article-featured-img.jpg",
    title: "International Journal of Research in Dermatology",
    excerpt:
      "Combination of systemic terbinafine (250 mg) twice daily and itraconazole (100 mg) twice in a pulse dose in resistant tinea infection",
    date: "March-April 2022",
    category: "ARTICLES",
    author: "Pro. Dr. S M A Shamim",
    designation: "Vol. 8, Issue-2",
    authorImg: "/images/author-image.png",
    isSave: false,
  },
  {
    id: 8,
    img: "/images/article-featured-img.jpg",
    title: "National Library of Medicine",
    excerpt:
      '"Lockdown Dermatoses" during COVID-19-A Series of 127 Patients from the Indian Subcontinent',
    date: "28 Feb, 2022",
    category: "ARTICLES",
    author: "Pro. Dr. S M A Shamim",
    designation: "Vol. 20, Issue-1",
    authorImg: "/images/author-image.png",
    isSave: false,
  },
  {
    id: 9,
    img: "/images/article-featured-img.jpg",
    title: "International Journal of Research in Dermatology",
    excerpt:
      "Approaching a Sad Face Presented in SAARC AAD In UAE, Aesthetic Evolution: A SAARC Perspective, World Trade Centre, Dubai – United Arab Emirates",
    date: "22 Sep 2023",
    category: "PANELIST, MODERATOR & WORKSHOP",
    author: "Pro. Dr. S M A Shamim",
    designation: "DUBAI",
    authorImg: "/images/author-image.png",
    isSave: false,
  },
  {
    id: 10,
    img: "/images/article-featured-img.jpg",
    title: "International Journal of Trichology",
    excerpt:
      "BIOLOGICS in Psoriasis : Bangladesh Scenario & My Approach to Treat Sad Face Presented in BANGLADERMA 2023, Siliguri, Darjeeling, West Bengal, India",
    date: "16 to 18 Jun 2023",
    category: "PANELIST, MODERATOR & WORKSHOP",
    author: "Pro. Dr. S M A Shamim",
    designation: "INDIA",
    authorImg: "/images/author-image.png",
    isSave: false,
  },
  {
    id: 11,
    img: "/images/article-featured-img.jpg",
    title: "Journal of Pakistan Association of Dermatologists",
    excerpt:
      "La Aesthetica – LEARN FROM THE EXPERTS – SAARC Association of Aesthetic Dermatology, LP VILAS, Dehradun, India",
    date: "8 to 9 April 2023",
    category: "PANELIST, MODERATOR & WORKSHOP",
    author: "Pro. Dr. S M A Shamim",
    designation: "INDIA",
    authorImg: "/images/author-image.png",
    isSave: false,
  },
  {
    id: 12,
    img: "/images/article-featured-img.jpg",
    title: "Skin Pharmacology and Physiology",
    excerpt:
      "FUE ASIA 2023 – Medical & Regenerative Trichology FUE Hair Transplant Workshop, The Leela Ambience, Gurugram, India",
    date: "09 to 11 Mar, 2023",
    category: "PANELIST, MODERATOR & WORKSHOP",
    author: "Pro. Dr. S M A Shamim",
    designation: "INDIA",
    authorImg: "/images/author-image.png",
    isSave: false,
  },
  {
    id: 13,
    img: "/images/article-featured-img.jpg",
    title: "Clinical, Cosmetic and Investigational Dermatology",
    excerpt:
      "4th International Conference on Psoriasis & Inflammatory Skin Disorders (In collaboration with SPIN Network) Evolving Knowledge of Chronic Inflammatory Skin Disorders by Psoriasis Awareness Club, Ballroom, Pan Pacific Sonargaon, Dhaka",
    date: "9 Feb 2023",
    category: "PANELIST, MODERATOR & WORKSHOP",
    author: "Pro. Dr. S M A Shamim",
    designation: "BANGLADESH",
    authorImg: "/images/author-image.png",
    isSave: false,
  },
  {
    id: 15,
    img: "/images/article-featured-img.jpg",
    title: "Pediatric Dermatology",
    excerpt:
      "Dubai Derma 2024, Dubai, UAE",
    date: "5 to 7 Jun, 2024",
    category: "SEMINAR, SYMPOSIUM, CONFERENCE",
    author: "Pro. Dr. S M A Shamim",
    designation: "UAE",
    authorImg: "/images/author-image.png",
    isSave: false,
  },
  {
    id: 18,
    img: "/images/article-featured-img.jpg",
    title: "Mycoses International Journal",
    excerpt:
      "Emerging Antifungal Resistance in Dermatophyte Infections: Clinical Implications and Treatment Modifications",
    date: "8 Sep, 2020",
    category: "ARTICLES",
    author: "Pro. Dr. S M A Shamim",
    designation: "Vol. 63, Issue-9",
    authorImg: "/images/author-image.png",
    isSave: false,
  },
  {
    id: 19,
    img: "/images/article-featured-img.jpg",
    title: "Annals of International Medical and Dental Research",
    excerpt:
      "Adverse Effects Encountered during the therapy of Topical Minoxidil combined with Systemic Finasteride and topical Minoxidil Alone in Male Androgenetic Alopecia",
    date: "May-June 2021",
    category: "ARTICLES",
    author: "Pro. Dr. S M A Shamim",
    designation: "Vol-7, Issue-3",
    authorImg: "/images/author-image.png",
    isSave: false,
  },
  {
    id: 20,
    img: "/images/article-featured-img.jpg",
    title: "MH Samorita Medical College Journal",
    excerpt: "Psoriasis with Multiple Comorbidities: A Case Report",
    date: "July 2020",
    category: "ARTICLES",
    author: "Pro. Dr. S M A Shamim",
    designation: "Vol. 03, Issue-02",
    authorImg: "/images/author-image.png",
    isSave: false,
  },
];
